data_root: "~/Documents/self_organization_percolation/SOP_data"

raw_dir: "raw"
manifest_dir: "manifests"
reduced_local_dir: "reduced_local"
published_dir: "published"
logs_dir: "logs"
tmp_dir: "tmp"

machine_name: null

publish_enabled: true
publish_machine: "light"

file_extensions:
  sample_json: ".json"
  sample_npy: ".npy"

group_keys:
  - type
  - nc
  - dim
  - L
  - NT
  - k
  - rho